# Generated by Django 4.1.7 on 2025-01-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robot", "0002_alter_telegramuser_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="bot_images/")),
            ],
        ),
        migrations.CreateModel(
            name="BotText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("geo", models.CharField(max_length=255)),
                ("traffic_type", models.CharField(max_length=255)),
                ("offer_link", models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="lang",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
