# Generated by Django 4.1.7 on 2025-01-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0003_botimage_bottext_offer_telegramuser_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='botimage',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bottext',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
