# Generated by Django 4.1.7 on 2025-02-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robot", "0006_communitybutton"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("url", models.URLField()),
            ],
        ),
    ]
